export default {
  APP_PORT: 3000,
  DEV_SERVER_PORT: 3001,
  APP_NAME: 'Twitcherino',

  APP_DOM_CONTAINER: 'react-view',

  ACTIONS: {
    SELECT_STREAMS: 'SELECT_STREAMS',
    REQUEST_STREAMS: 'REQUEST_STREAMS',
    RECEIVE_STREAMS: 'RECEIVE_STREAMS'
  }
};