export default {
  APP_PORT: 3000,
  APP_NAME: 'Twitcherino',

  APP_DOM_CONTAINER: 'react-view',

  ACTIONS: {
    BUY_DRUG: 'BUY_DRUG',
    CHANGE_DRUG: 'CHANGE_DRUG',
    CHANGE_CASH: 'CHANGE_CASH',
    CHANGE_DAY: 'CHANGE_DAY',
    CHANGE_WHOLE_LIST: 'CHANGE_WHOLE_LIST',
    ADD_BACKPACK_ITEM: 'ADD_BACKPACK_ITEM',
    CHANGE_BACKPACK_ITEM: 'CHANGE_BACKPACK_ITEM',
    DELETE_BACKPACK_ITEM: 'DELETE_BACKPACK_ITEM',
    CHANGE_MODAL_INFOS: 'CHANGE_MODAL_INFOS',
    BUILD_TOMORROW_LIST: 'BUILD_TOMORROW_LIST',
    BUILD_TOMORROW_MESSAGES: 'BUILD_TOMORROW_MESSAGES'
  }
};