export default {
  APP_PORT: 3000,
  DEV_SERVER_PORT: 3001,
  APP_NAME: 'Twitcherino',

  APP_DOM_CONTAINER: 'react-view',

  DEBONCE_TIMER: 300,
  SCROLL_LOAD_OFFSET: 1000,
  NUMBER_STREAM_FETCH: 25,

  ACTIONS: {
    REQUEST_STREAMS: 'REQUEST_STREAMS',
    RECEIVE_STREAMS: 'RECEIVE_STREAMS',
    REQUEST_GAMES: 'REQUEST_GAMES',
    RECEIVE_GAMES: 'RECEIVE_GAMES',
    CLEAR_STREAM_LIST: 'CLEAR_STREAM_LIST',
    CLEAR_GAME_LIST: 'CLEAR_GAME_LIST',
    REQUEST_USER: 'REQUEST_USER',
    RECEIVE_USER: 'RECEIVE_USER',
    UPDATING_USER: 'UPDATING_USER',
    UPDATED_USER: 'UPDATED_USER'
  }
};